project:
  type: website
  output-dir: docs

website:
  title: "Anna Xu"
  navbar:
    right:
      - text: "What is this blog?"
        href: about.qmd
      - text: "Homepage"
        icon: globe
        href: https://anna-xu.github.io/
format:
  html:
    theme: simplex
    css: styles.css